name: Build and Test with ROS1

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "noetic"
            container:
              image: "ghcr.io/fixposition/fixposition-sdk:noetic-ci"

    container: ${{ matrix.config.container }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          path: src/fixposition_driver
      - name: Ignore ROS2 node
        run: |
          touch src/fixposition_driver/fixposition_driver_ros2/CATKIN_IGNORE
          touch src/fixposition_driver/fixposition_odometry_converter_ros2/CATKIN_IGNORE
      - name: Init Workspace
        run: |
          catkin init
      - name: Build and Test
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin build fixposition_driver_lib fixposition_driver_ros1 fixposition_odometry_converter_ros1 --force-cmake -DBUILD_TESTING=ON
          catkin run_tests
