name: Build and Test with ROS2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "humble"
            container:
              image: "ghcr.io/fixposition/fixposition-sdk:humble-ci"
          - name: "jazzy"
            container:
              image: "ghcr.io/fixposition/fixposition-sdk:jazzy-ci"

    container: ${{ matrix.config.container }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          path: src/fixposition_driver
      - name: Ignore ROS1 node
        run: |
          touch src/fixposition_driver/fixposition_driver_ros1/COLCON_IGNORE
          touch src/fixposition_driver/fixposition_odometry_converter_ros1/COLCON_IGNORE
      - name: Build and Test
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon build --packages-up-to fixposition_driver_ros2 --cmake-args -DBUILD_TESTING=ON
          colcon test --packages-up-to fixposition_driver_ros2
